### PR TITLE
Handle Ctrl-C while having `pick(1)` open

### PR DESCRIPTION
**Pull request by teoljungberg**
In [pick#240] support was added to handle Ctrl-C, this commit fixes that
behavior in the vim plugin to not crash with an error when that happens.

Since `pick(1)` now swallows ctrl-c and handles it internally. We can remove the outmost try/catch dance.

[pick#240]: https://github.com/calleerlandsson/pick/pull/240

### CODE REVIEW

**Comment by teoljungberg** [comment]
Ping @mptre

**Comment by mptre** [comment]
I would guess this is caused by the fact that there's no signaling going
anymore while pressing ^C; pick will instead exit, although with an
erroneous status. It should therefore be sufficient to examine the exit
code in order to determine success/failure. Catching the out-of-bounds
exception looks scary IMHO.

See diff below. Don't know if the  whole interrupt try/catch wrapper is
no longer needed either.

```diff
--- pick.vim.orig	Wed Sep 20 15:38:21 2017
+++ pick.vim	Wed Sep 20 15:38:42 2017
@@ -10,11 +10,19 @@
   try
     let pick_command = a:choice_command . " | " . g:pick_executable . " " . a:pick_args
     if exists("*systemlist")
-      let selection = systemlist(pick_command)[0]
+      let selection = systemlist(pick_command)
+      if v:shell_error == 0
+        let selection = selection[0]
+      else
+        let selection = ''
+      endif
     else
       let selection = substitute(system(pick_command), '\n$', '', '')
     endif
     redraw!
+    if empty(selection) == 0
+      return
+    endif
 
     if a:escapable_output > 0
       let escaped_selection = fnameescape(selection)
@@ -22,12 +30,10 @@
       let escaped_selection = selection
     endif
 
-    if v:shell_error == 0
-      try
-        exec a:vim_command . " " . escaped_selection
-      catch /E325/
-      endtry
-    endif
+    try
+      exec a:vim_command . " " . escaped_selection
+    catch /E325/
+    endtry
   catch /Vim:Interrupt/
     " Swallow the ^C so that the redraw below happens; otherwise there will be
     " leftovers from pick on the screen
```

**Comment by teoljungberg** [comment]
@mptre Valid point. My fear with that approach would be that the vim versions without `systemlist` would still need the already present error handling (the `v:shell` logic that was moved).

Do you see any ways out of that?

**Comment by mptre** [comment]
Why not let older versions of Vim mimic `systemlist()`:

```diff
--- pick.vim.orig	Wed Sep 20 15:57:52 2017
+++ pick.vim	Wed Sep 20 16:05:23 2017
@@ -10,11 +10,15 @@
   try
     let pick_command = a:choice_command . " | " . g:pick_executable . " " . a:pick_args
     if exists("*systemlist")
-      let selection = systemlist(pick_command)[0]
+      let selection = systemlist(pick_command)
     else
-      let selection = substitute(system(pick_command), '\n$', '', '')
+      let selection = split(system(pick_command), "\n")
     endif
     redraw!
+    if v:shell_error != 0 || len(selection) == 0
+      return
+    endif
+    let selection = selection[0]
 
     if a:escapable_output > 0
       let escaped_selection = fnameescape(selection)
@@ -22,12 +26,10 @@
       let escaped_selection = selection
     endif
 
-    if v:shell_error == 0
-      try
-        exec a:vim_command . " " . escaped_selection
-      catch /E325/
-      endtry
-    endif
+    try
+      exec a:vim_command . " " . escaped_selection
+    catch /E325/
+    endtry
   catch /Vim:Interrupt/
     " Swallow the ^C so that the redraw below happens; otherwise there will be
     " leftovers from pick on the screen
```

**Comment by teoljungberg** [comment]
After some testing, it seems to work pretty finely. And yes, we could we remove the outmost try catch histroy.

**Comment by teoljungberg** [comment]
I pushed a last fix, that now works with all of the if branches.

What do you think @mptre?

**Comment by mptre** [comment]
I'm more in favor of my previous diff.

**Comment by teoljungberg** [comment]
I tried out your diff in https://github.com/calleerlandsson/pick.vim/pull/21#issuecomment-330862647 and found this on an older version of vim `7.4.8056`.

```viml
Error detected while processing function PickFile[1]..PickCommand:                                                                                                                                                                     
line   12:                                                                                                                                                                                                                             
E706: Variable type mismatch for: selection                                                                                                                                                                                            
```

We cannot re-set the `selection` variable from a list to a string.

Changing it to:

```diff
diff --git a/plugin/pick.vim b/plugin/pick.vim
index 7eefe6e..15389a5 100644
--- a/plugin/pick.vim
+++ b/plugin/pick.vim
@@ -10,15 +10,15 @@ function! PickCommand(choice_command, pick_args, vim_command, escapable_output)
   try
     let pick_command = a:choice_command . " | " . g:pick_executable . " " . a:pick_args
     if exists("*systemlist")
-      let selection = systemlist(pick_command)
+      let files = systemlist(pick_command)
     else
-      let selection = split(system(pick_command), "\n")
+      let files = split(system(pick_command), "\n")
     endif
     redraw!
-    if v:shell_error != 0 || len(selection) == 0
+    if v:shell_error != 0 || len(files) == 0
       return
     endif
-    let selection = selection[0]
+    let selection = files[0]

     if a:escapable_output > 0
       let escaped_selection = fnameescape(selection)
```

Makes things green in all branches.

I'm fine with your diff aswell, with my addition to make it green.

**Comment by mptre** [comment]
> I'm fine with your diff aswell, with my addition to make it green.

Makes sense and looks good.

**Comment by teoljungberg** [comment]
Great. I'm force-pushing and merging, thanks for working with me in this @mptre!

**Pull request merged**
