### PR TITLE
Invoke the alternative screen for `pick` by default

### PR DESCRIPTION
**Pull request by teoljungberg**
Which simplifies the C code in [thoughtbot/pick](https://github.com/thoughtbot/pick).

### CODE REVIEW

**Comment by calleluks** [comment]
Looks good to me!

**Comment by teoljungberg** [comment]
@calleerlandsson Should we wait on merging this until the new version of pick is released? Or are there any compatibility issues with having both `pick(1)` and `pick.vim` checking for the presence of the alternate screen?

**Comment by calleluks** [comment]
No, merging this now should be completely fine.

**Comment by teoljungberg** [comment]
Thanks, Calle.

**Pull request merged**
