### PR TITLE
Add `PickBufferCommand` to allow customization

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by teoljungberg** [comment]
@calleerlandsson What do you think of making this function public to allow customization? That would resolve #11, and #8 without adding any new commands.

**Comment by calleluks** [comment]
Is this so that you can get the same buffer list pick.vim uses for it's pick buffer command to use in a call to  `PickCommand`?

**Comment by teoljungberg** [comment]
@calleerlandsson That's right. That way, the user would be able to add new commands for working with buffers using the same function `pick.vim` uses.

Since we are making the function public, what do you think about renaming it to `PickBufferListCommand` to avoid any collisions? Or is that overthinking things?

**Comment by calleluks** [comment]
@teoljungberg That makes sense. My only concern is that this might be exposing implementation details of pick.vim. If this is valid or not, I'm not sure.

Here's another possible solution that I just thought of:

```
function! PickBufferCommand(vim_command)
  call PickCommand(s:BufferListCommand(), "", a:vim_command)
endfunction
```

I could definitely go either way on this and would even be fine implementing all the additional commands we have for files like in #8. It's your call.

**Comment by teoljungberg** [comment]
@calleerlandsson Interesting thought. I think I'll go down the route of renaming the buffer command `PickBufferListCommand` for now.

**Comment by teoljungberg** [comment]
@calleerlandsson Or, I really like the latter idea you suggested. I'm going for that instead!

**Pull request merged**
